language: python
dist: xenial
sudo: true
python:
- '3.7'
- "3.8"
install:
- python setup.py install
before_script:
- pip install nox
script:
- nox
stages:
- test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: test
  - stage: deploy
    python: '3.7'
    script: skip
    deploy:
      provider: pypi
      user: kirillsulim
      password:
        secure: "CXpIZ+3DeJzp+bs5hGt9Yi4WdqQKForx3TPjDvofr+SXxPc59e8/gBFyn7/hQtEkeZXnMW6TqaEivxJLsMm8C+5Fz+ZeqK9hogSJnuk4vLPzQAWAHRUPqjWYRlsOZ/NDIm+w5p2WMrcWDw4sLhE5hQ8XwdflpUoE4fkA6NOtDdffwVA03XvAzffFCT4wX/zWxvPkpCjzbyPT/pVIjhgtF/pW7gyRT1olI96R7rwGjqLu24KFqlzECnmqAO5eg80zav6QAsNos+nUWbqvEfYdt8MGVAibTB9bqRjfR6PnT/02WQ8tHKthArqnlQxeUr/30rUKtP57NtvvgEPrOoBYVAZiEbTXjT+ZOBMchKqhPRgu+toMsoO9ODsfEuKbB3ONQPyxna00sL/IZqhzzjza/FlJ6iUVTaJYG978NtTe+jEYDBJqfoCmfrIXXzAeE3Q8sh3bH1BCoJ7z6nySG5OjXrxL0GZfEhInBZoczFI5JH52iWnbQM1NWpAGcramKW/fdi9iDLuS6Kiq0hU3fjRSudalDyu5hl+CvH5hzNGxvoYwZe3JEJWsPY3jYWwLtVmJuz4iLKSOzr5K6SKCn7+JlXvfb9r+yvQAR2UIv2iF9bqCp0gn9lw7HsIYcPv+avUZPucfUfjbPM8FpF0G0JZgxfVpPU3tSn7lvKs1/LFoOIU="
      on:
        distributions: sdist bdist_wheel
        repo: dogebuild/dogebuild-c
